# Reload Configuration
unbind r
bind r source-file ~/.tmux.conf

# Change leader from C-b to C-a
set -g prefix C-a

# Enable mouse (for sizing and motions)
set -g mouse on

# Vim motions when scrolling
set-window-option -g mode-keys vi
bind-key -T copy-mode-vi v send -X begin-selection
bind-key -T copy-mode-vi V send -X select-line
bind-key -T copy-mode-vi y send -X copy-pipe-and-cancel 'xclip -in -selection clipboard'

# Panes motion like vim
bind-key h select-pane -L
bind-key j select-pane -D
bind-key k select-pane -U
bind-key l select-pane -R

# Start counting pane and window number at 1
set -g base-index 1
setw -g pane-base-index 1
set -g renumber-windows on

# List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'

# vim-tmux navigator
set -g @plugin 'christoomey/vim-tmux-navigator'

# TODO: bind cmd + t to create newwindow
# TODO: bind cmd + num to move around windows

# Enable extended key sequence (needed by pi)
set -g extended-keys on

# Source local overrides
if-shell "[ -f ~/.tmux.conf.local ]" "source-file ~/.tmux.conf.local"

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'
