# Reload Configuration
unbind r
bind r source-file ~/.tmux.conf

# Automatic window naming
set-option -g automatic-rename on
set-option -g automatic-rename-format '#{b:pane_current_path}'

# Change leader from C-b to C-a
set -g prefix C-a

# Enable mouse (for sizing and motions)
set -g mouse on

# Vim motions when scrolling
set-window-option -g mode-keys vi
bind-key -T copy-mode-vi v send -X begin-selection
bind-key -T copy-mode-vi V send -X select-line
bind-key -T copy-mode-vi y send -X copy-pipe-and-cancel 'xclip -in -selection clipboard'

# Panes motion like vim
bind-key h select-pane -L
bind-key j select-pane -D
bind-key k select-pane -U
bind-key l select-pane -R

# Start counting pane and window number at 1
set -g base-index 1
setw -g pane-base-index 1
set -g renumber-windows on

# Select window or create if it does not exist (letting tmux assign the next slot sequentially)
bind-key 1 if-shell 'tmux select-window -t :1' '' 'new-window'
bind-key 2 if-shell 'tmux select-window -t :2' '' 'new-window'
bind-key 3 if-shell 'tmux select-window -t :3' '' 'new-window'
bind-key 4 if-shell 'tmux select-window -t :4' '' 'new-window'
bind-key 5 if-shell 'tmux select-window -t :5' '' 'new-window'
bind-key 6 if-shell 'tmux select-window -t :6' '' 'new-window'
bind-key 7 if-shell 'tmux select-window -t :7' '' 'new-window'
bind-key 8 if-shell 'tmux select-window -t :8' '' 'new-window'
bind-key 9 if-shell 'tmux select-window -t :9' '' 'new-window'
bind-key 0 if-shell 'tmux select-window -t :10' '' 'new-window'



# List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'

# vim-tmux navigator
set -g @plugin 'christoomey/vim-tmux-navigator'

# TODO: bind cmd + t to create newwindow
# TODO: bind cmd + num to move around windows

# Enable extended key sequence (needed by pi)
set -g extended-keys on
set -g extended-keys-format csi-u

# Source local overrides
if-shell "[ -f ~/.tmux.conf.local ]" "source-file ~/.tmux.conf.local"

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'
